name: hotel_booking
description: "Приложение для резервирования отелей"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_bloc: ^8.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
